# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f653d510b92453bcd1f8b72745990d348ac5ba31ee5e61ffc33a6d0e6cd71c2e9baf3a25153f6d56bece28fa38682b86c58c35035f4d69ecab57a0cf1d093291

test:
  secret_key_base: f547b66153b87e4514ecaf3ecaeda408ff3be2a97718532717332133b12ba894109e6473b5f729bbff7b63d78cee5adc36f18dcebe41cd71b9a525e914d8b7d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
